window.RENOWEET_PROJECTS=[
  {
    "id": "project-amsterdam-01",
    "title_nl": "Renovatie & technische afbouw",
    "title_en": "Renovation & technical fit-out",
    "location": "Amsterdam",
    "year": "2026",
    "type_nl": "Renovatie • Timmerwerk • Techniek",
    "type_en": "Renovation • Carpentry • Technical",
    "summary_nl": "Voorbeeldproject. Vervang deze tekst en foto's via Renoweet Website Manager.",
    "summary_en": "Example project. Replace this text and photos using Renoweet Website Manager.",
    "challenge_nl": "Een bestaande ruimte opnieuw indelen met aandacht voor bouwkundige afwerking en technische installaties.",
    "challenge_en": "Reconfigure an existing space while coordinating construction finishes and technical services.",
    "solution_nl": "Renoweet combineert voorbereiding, timmerwerk, technische aanpassingen en nette afwerking in één afgestemde uitvoering.",
    "solution_en": "Renoweet combines preparation, carpentry, technical modifications and clean finishing in one coordinated delivery.",
    "photos": []
  },
  {
    "id": "project-amsterdam-02",
    "title_nl": "Timmerwerk & maatwerk",
    "title_en": "Carpentry & custom work",
    "location": "Amsterdam & omgeving",
    "year": "2026",
    "type_nl": "Timmerwerk • Afbouw",
    "type_en": "Carpentry • Finishing",
    "summary_nl": "Voorbeeldproject voor maatwerk, deuren, wanden of andere afbouw.",
    "summary_en": "Example project for custom carpentry, doors, partitions or other finishing work.",
    "challenge_nl": "Een praktische oplossing realiseren die technisch klopt en netjes aansluit op de bestaande situatie.",
    "challenge_en": "Create a practical solution that works technically and integrates neatly with the existing situation.",
    "solution_nl": "Maatvoering, voorbereiding en uitvoering worden als één geheel bekeken voor een strak eindresultaat.",
    "solution_en": "Measurement, preparation and execution are treated as one process for a clean final result.",
    "photos": []
  },
  {
    "id": "project-amsterdam-03",
    "title_nl": "Technische renovatieoplossing",
    "title_en": "Technical renovation solution",
    "location": "Amsterdam",
    "year": "2026",
    "type_nl": "Techniek • Renovatie",
    "type_en": "Technical • Renovation",
    "summary_nl": "Voorbeeld van een klus waar bouw en techniek samenkomen.",
    "summary_en": "Example of a project where construction and technical work come together.",
    "challenge_nl": "Meerdere disciplines moesten op elkaar aansluiten zonder onnodige tussenlagen of miscommunicatie.",
    "challenge_en": "Several disciplines needed to work together without unnecessary hand-offs or miscommunication.",
    "solution_nl": "Eerst de technische samenhang begrijpen, daarna gericht en praktisch uitvoeren.",
    "solution_en": "Understand the technical dependencies first, then execute in a focused, practical way.",
    "photos": []
  }
];
